version: '3'

services:
  redis-server:
    image: 'redis'

  postgres:
    env_file:
      - .env
    image: 'postgres'
    ports:
    - 5433:${PG_PORT}
    volumes:
      - ./dbinit:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_DB: "${PG_DB}"
      POSTGRES_PASSWORD: "${PG_PASSWORD}"
      POSTGRES_HOST_AUTH_METHOD: "trust"

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  go-app:
    build: .
    env_file:
      - .env
    ports:
      - "${EXPOSE_PORT}:${CONTAINER_PORT}"